// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package entity

type Comment struct {
	ID        int        `json:"id"`
	Author    string     `json:"author"`
	Content   string     `json:"content"`
	CreatedAt int        `json:"created_at"`
	Comments  []*Comment `json:"comments"`
}

type Mutation struct {
}

type Post struct {
	ID           int        `json:"id"`
	Author       string     `json:"author"`
	Title        string     `json:"title"`
	Content      string     `json:"content"`
	AllowComment bool       `json:"allowComment"`
	CreatedAt    int        `json:"created_at"`
	Comments     []*Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}
